#
# Copyright IBM Corp All Rights Reserved
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  basic:

services:
  orderer1:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_FILELEDGER_LOCATION=/tmp/hyperledger/orderer
      - BLOCK_SIZE=${BLOCK_SIZE}
      - TXN_SPAN_LIMIT=${TXN_SPAN_LIMIT}
      - SCHEDULER_TYPE=${CC_TYPE}
      - STORE_PATH=/data/mvstore

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: /bin/bash -c 'orderer 2>&1 | tee /log/orderer.log '
    ports:
      - 7041:7050
    volumes:
        - ./channel_artifacts/:/etc/hyperledger/configtx
        - ./crypto_config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/msp/orderer
        - ./crypto_config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/msp/peerOrg1
        - ./log:/log
    networks:
      - basic

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=simple-docker_basic
      - SCHEDULER_TYPE=${CC_TYPE}

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash -c 'peer node start 2>&1 | tee /log/peer.log'
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto_config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/msp/peer
        - ./crypto_config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
        - ./log:/log
        # - ./config:/etc/hyperledger/configtx
    depends_on:
      - orderer1
    networks:
      - basic